server:
  port: 8094
  servlet:
    context-path: /
spring:
  application:
    name: cart-service
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

#mybatis-plush配置
mybatis-plus:
    #别名包  简化类型转化的写法
  type-aliases-package: com.jt.pojo
    #加载mybatis的映射文件
  mapper-locations: classpath:/mappers/*.xml
    #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#引入日志
logging:
  level:
    com.jt.mapper: debug
      
  
